default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  host: 127.0.0.1

development:
  <<: *default
  database: ads_development

test:
  <<: *default
  database: ads_test

production:
  <<: *default
